name: Tests and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        cd src
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        cd src
        pytest test.py

  deploy:
    runs-on: ubuntu-latest
    needs: ['tests']
    if: github.ref == 'refs/heads/main'
    steps:
     - uses: actions/checkout@v4
     - name: Clear tests directory
       run: rm -r ./src/tests
     - name: Deploy Function
       uses: yc-actions/yc-sls-function@v2
       with:
         yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
         folder-id: 'b1gvdf9o5vknfjmt10ij'
         function-name: 'uunit-schedule'
         runtime: 'python39'
         memory: '128Mb'
         source-root: './src'
         entrypoint: 'main.handler'
         tags: |
           latest
